## makeCacheMatrix generates a list of functions that store and retrieve the data and its inverse within its closure.
## cacheSolve takes a list generated by makeCacheMatrix as input and calculate the inverse of data only if it hasn't been calculated before. 

## This function returns a list of functions that operate on the data and its inverse. 

makeCacheMatrix <- function(x = matrix()) {
  inv<-NULL
  set<-function(y){
    x<<-y
    inv<<-NULL
  }
  get <- function() x
  setinv<-function(inv_mat) inv<<-inv_mat
  getinv<-function() inv
  list(set=set, get=get, setinv=setinv, getinv=getinv)
}


## This function checks for a previously solved inverse and return it if it exists. Else, it solves for the inverse, stores it and return it.

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inv<-x$getinv()
  if(!is.null(inv)){
    message('getting cached inverse')
    return(inv)
  }
  data<-x$get()
  inv<-solve(data, ...)
  x$setinv(inv)
  inv
}


